site_name: Ultimate Terraform Bootcamp
docs_dir: chapters
plugins: 
  - search
pages:
  - Home: index.md
  - Setup:
    - Setting up the environment: "00-environment-setup.md"
  - Getting Started with Terraform:
    - Getting Started: "01-getting-started.md"
    - Important Commands: "02-terraform-important-commands.md"
    - Terraform Providers: "03-providers.md"
    - Terraform Building Blocks - Part 1: "04-resources-part1.md"
    - Terraform Building Blocks - Part 2: "05-resources-part2.md"
    - Input and Output Variables: "06-variables-and-outputs.md"
    - Provisioners in detail: "07-provisioners.md"
    - Data Source: "07-datasources.md"
    - Terrafrom State: "09-terraform-state.md"
    - Backend and Statelocking: "10-backends.md"
    - State Management in Terraform: "0x-terraform-state.md"
theme: readthedocs

